# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
name: unit_tests

on:
  pull_request:
    paths:
      - 'api/**'
      - 'cmd/**'
      - 'pkg/**' 
      - 'internal/**' 

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
                  go test ./... -v -cover
